set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]

# AX7103 PCIe reference clock and PERST#.
create_clock -period 10.000 -name pcie_refclk [get_ports pcie_refclk_clk_p]
set_property PACKAGE_PIN F10 [get_ports pcie_refclk_clk_p]
set_property PACKAGE_PIN J20 [get_ports pcie_perst_n]
set_property IOSTANDARD LVCMOS33 [get_ports pcie_perst_n]
set_property PULLUP true [get_ports pcie_perst_n]
set_false_path -from [get_ports pcie_perst_n]

# AX7103 200-MHz board clock and reset. DDR3 pins come from ax7103_mig.prj.
create_clock -period 5.000 -name ddr_refclk [get_ports ddr_refclk_clk_p]
set_property PACKAGE_PIN R4 [get_ports ddr_refclk_clk_p]
set_property PACKAGE_PIN T4 [get_ports ddr_refclk_clk_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr_refclk_clk_p ddr_refclk_clk_n}]
set_property PACKAGE_PIN T6 [get_ports board_reset_n]
set_property IOSTANDARD LVCMOS15 [get_ports board_reset_n]

# AN9238 on AX7103 J13. The FPGA drives the two ADC clock inputs.
set_property PACKAGE_PIN T18 [get_ports adc_clk_ch0]
set_property PACKAGE_PIN W16 [get_ports adc_clk_ch1]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_clk_ch0 adc_clk_ch1}]
set_property SLEW FAST [get_ports {adc_clk_ch0 adc_clk_ch1}]

set_property PACKAGE_PIN W21 [get_ports {adc_ch0[0]}]
set_property PACKAGE_PIN W22 [get_ports {adc_ch0[1]}]
set_property PACKAGE_PIN U21 [get_ports {adc_ch0[2]}]
set_property PACKAGE_PIN T21 [get_ports {adc_ch0[3]}]
set_property PACKAGE_PIN Y22 [get_ports {adc_ch0[4]}]
set_property PACKAGE_PIN Y21 [get_ports {adc_ch0[5]}]
set_property PACKAGE_PIN W19 [get_ports {adc_ch0[6]}]
set_property PACKAGE_PIN W20 [get_ports {adc_ch0[7]}]
set_property PACKAGE_PIN Y18 [get_ports {adc_ch0[8]}]
set_property PACKAGE_PIN Y19 [get_ports {adc_ch0[9]}]
set_property PACKAGE_PIN U22 [get_ports {adc_ch0[10]}]
set_property PACKAGE_PIN V22 [get_ports {adc_ch0[11]}]

set_property PACKAGE_PIN W15 [get_ports {adc_ch1[0]}]
set_property PACKAGE_PIN V17 [get_ports {adc_ch1[1]}]
set_property PACKAGE_PIN W17 [get_ports {adc_ch1[2]}]
set_property PACKAGE_PIN U15 [get_ports {adc_ch1[3]}]
set_property PACKAGE_PIN V15 [get_ports {adc_ch1[4]}]
set_property PACKAGE_PIN AB21 [get_ports {adc_ch1[5]}]
set_property PACKAGE_PIN AB22 [get_ports {adc_ch1[6]}]
set_property PACKAGE_PIN AA21 [get_ports {adc_ch1[7]}]
set_property PACKAGE_PIN AA20 [get_ports {adc_ch1[8]}]
set_property PACKAGE_PIN AB20 [get_ports {adc_ch1[9]}]
set_property PACKAGE_PIN AA19 [get_ports {adc_ch1[10]}]
set_property PACKAGE_PIN AA18 [get_ports {adc_ch1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_ch0[*] adc_ch1[*]}]
set_property IOB TRUE [get_ports {adc_ch0[*] adc_ch1[*]}]
